from graph import*
from math import*
def sun(x0, y0, radius, n, percent):
    A = [(0,0)]*n*2
    for k in range(n):
        A[k*2] = (x0 + radius * cos(2 * pi * k / n),y0 + radius * sin(2 * pi * k / n))
        A[k*2+1] = ( x0 + radius * percent * cos(2 * pi * k / n + pi / n),y0 + radius * percent * sin(2 * pi * k / n + pi / n))
    penColor("black")
    brushColor("yellow")
    polygon(A)
def tree(x, y, size):
    penColor("black")
    brushColor("saddlebrown")
    rectangle(x - size/2, y - size*5, x + size/2, y)
    penColor("black")
    brushColor("green")
    circle(x, y - size*9, size*1.5)
    circle(x + size*1.7, y - size*7.5, size*1.5)
    circle(x - size*1.7, y - size*7.5, size*1.5)
    circle(x, y - size*6.5, size*1.5)
    circle(x - size*1.5, y - size*5, size*1.5)
    circle(x + size*1.5, y - size*5, size*1.5)
def cloud(x, y, radius):
    penColor("black")
    brushColor("white")
    circle(x, y, radius)
    circle(x + radius, y, radius)
    circle(x + radius*2, y, radius)
    circle(x + radius*3, y, radius)
    circle(x + radius*2, y - radius*4/5, radius)
    circle(x + radius, y - radius*4/5, radius)
def house(x, y, size):
    penColor("black")
    brushColor("darkgoldenrod")
    rectangle(x - size/2, y - size*8/11, x + size/2, y)
    penColor("black")
    brushColor("darkcyan")
    rectangle(x - size*0.125, y - size*5/11, x + size*0.125, y - size*3/11)
    penColor("black")
    brushColor("brown")
    polygon([(x - size/2, y - size*8/11), (x, y - size*13/11), (x + size/2, y - size*8/11), (x - size/2, y - size*8/11)])
windowSize(455, 300)
canvasSize(455, 300)
penColor("lightskyblue")
brushColor("lightskyblue")
rectangle(0, 0, 455, 150)
penColor("forestgreen")
brushColor("forestgreen")
rectangle(0, 150, 455, 300)
sun(50, 50, 40, 20, 0.3)
cloud(150, 50, 15)
cloud(250, 80, 10)
cloud(350, 70, 18)
house(110, 220, 110)
tree(200, 210, 10)
house(300, 200, 70)
tree(360, 190, 7)
run()
